name: Linux tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Linux-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup
      run: ${{github.workspace}}/scripts/setup.sh

    - name: Run unit tests
      run: ${{github.workspace}}/venv/bin/python3 -m unittest discover ${{github.workspace}}/test

    - name: Run simple example
      run: ${{github.workspace}}/venv/bin/python3 ${{github.workspace}}/example/simple_expanen_example.py

    - name: Run advanced example
      run: ${{github.workspace}}/venv/bin/python3 ${{github.workspace}}/example/advanced_expanen_example.py